// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/login";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./protectedRoute/protectedRoute.tsx": {
    id: "protectedRoute/protectedRoute";
    page: "/";
  };
  "./routes/astrology.tsx": {
    id: "routes/astrology";
    page: "/";
  };
};